### ISSUE TITLE
Develop Next.js API Route for Dynamic PDF Certificate Generation

### ISSUE THREAD

**Issue by mgm1313** [buchungapp/nationaal-watersportdiploma#129]
We need a route handler in our Next.js application to facilitate the printing of certificates on pre-designed paper. This handler will be located at apps/web/src/app/api/generate-certificates/route.ts and should accept an array of certificate IDs. It will output a downloadable PDF containing the certificate details.

Initially, we can utilize a mock array of certificate data since the actual route isn't implemented yet. For converting data to a PDF, we have options like [react-pdf](https://react-pdf.org/), [PDF-LIB](https://pdf-lib.js.org/), and [PDFKit](https://pdfkit.org/). We need to determine which library best fits our needs for quality and performance.

**Resources:**
- Example output: [diploma-print-mock.pdf](https://github.com/buchungapp/nationaal-watersportdiploma/files/15089883/diploma-print-mock.pdf)
- For the actual print layout, please contact me directly.

**Requirements:**
- Create a Next.js route handler at the specified path.
- The handler takes an array of certificate IDs and returns a PDF.
- Use a mock data array for initial testing.
- Decide on the PDF generation library based on our requirements.

**Comment by mgm1313** [comment]
I'm unsure if tools like Acrobat can extract the dimensions, font sizes, and weights directly from the PDF. If not, let me know, and I'll provide a detailed list from the original InDesign file.

**Comment by tomasfrancisco** [comment]
[React-pdf](https://react-pdf.org/) is more geared towards rendering pdf in browser.
[PDF-LIB](https://pdf-lib.js.org/) hasn't received updates in 3 years - which makes it a less interesting library to use in the long run.
[pdfmake](https://github.com/bpampuch/pdfmake) - more recent (3 yo), more popular it seems.
[PDFKit](https://pdfkit.org/) is 10 yo, but seems to receive some updates.
[jsPDF](https://github.com/parallax/jsPDF) - is the most popular, no code updates since last year

**Comment by mgm1313** [comment]
![CleanShot 2024-04-24 at 11 58 32](https://github.com/buchungapp/nationaal-watersportdiploma/assets/9018689/153521d1-6706-4785-869b-859451413a5d)
[source](https://npmtrends.com/jspdf-vs-pdf-lib-vs-pdfkit-vs-pdfmake-vs-react-pdf)

I don’t have a strong preference regarding the options. Based on your review of their documentation, which option do you find to be the most developer-friendly? Our use case isn’t particularly advanced, so any of the options should suffice. Let’s choose the one that provides the best experience for developers.

**Comment by tomasfrancisco** [comment]
Currently playing with jsPDF as I've seen it being used in the past projects and seems to have good documentation. Another option we could consider is also creating it in HTML, and then converting to PDF. This would allow for easy stylings making use of CSS which then simply gets converted to PDF. What do you think?

@mgm1313

**Comment by tomasfrancisco** [comment]
@mgm1313 PR is ready!

**Comment by mgm1313** [comment]
Merged with https://github.com/buchungapp/nationaal-watersportdiploma/pull/139, thanks again!
